# Generated by Django 4.2.5 on 2023-09-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla'), ('cinnamon sugar', 'Cinnamon Sugar'), ('fruit-filled', 'Fruit-filled'), ('red velvet', 'Red velvet'), ('salted-caramel', 'Salted caramel'), ('peanut-butter', 'Peanut Butter'), ('mocha', 'Mocha')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='donut_images/')),
            ],
        ),
    ]
