# Generated by Django 4.2.4 on 2023-10-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_donuts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donut',
            name='category',
            field=models.CharField(choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla'), ('fruit-filled', 'Fruit-filled'), ('red velvet', 'Red velvet'), ('salted-caramel', 'Salted caramel'), ('peanut-butter', 'Peanut Butter'), ('matcha', 'Matcha')], max_length=50),
        ),
    ]
