# Generated by Django 4.2.4 on 2023-10-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_donuts', '0002_alter_donut_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donut',
            name='category',
            field=models.CharField(choices=[('Chocolate', 'Chocolate'), ('Vanilla', 'Vanilla'), ('Fruit-filled', 'Fruit-filled'), ('Red velvet', 'Red velvet'), ('Salted caramel', 'Salted caramel'), ('Peanut butter', 'Peanut Butter'), ('Matcha', 'Matcha')], max_length=50),
        ),
    ]
